name: Upload Example Artifact

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Removed step to create example.txt, as we will upload data.json instead

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: data.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
