name: Upload Example Artifact

on:
  push:
    branches:
      - master

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create example file
        run: echo "This is an example file." > example.txt

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: example.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
